
import React from 'react'
import { Text } from 'ink'

interface ErrorViewOpts {
  message: string
}

/**
 * View errors generated by the application.
 *
 * @param opts view options
 *
 * @returns
 */
export function ErrorView (opts: ErrorViewOpts): any {
  return (
    <>
      <Text>Error: {opts.message}</Text>
    </>
  )
}
